import type { Argument, Message, OutputFile } from "./types";

/**
 * Pretty JSON — also a valid JavaScript expression, so it doubles as the
 * literal an emitted module exports.
 */
export const json = (value: unknown): string => {
  return JSON.stringify(value, null, 2);
};

/** The banner atop every emitted module. */
export const banner = (): string => {
  return "// Generated by @fibber/kit. Do not edit by hand.";
};

/** A string-literal union, one member per line; `never` when empty. Follows a bare `=`. */
export const union = (members: string[]): string => {
  if (members.length === 0) {
    return " never";
  }
  return members.map((member) => `\n  | ${JSON.stringify(member)}`).join("");
};

/**
 * The type a caller passes for one argument. A select lists its options for
 * completion yet stays open to any string, since `other` catches the rest.
 */
export const type = (argument: Argument): string => {
  switch (argument.kind) {
    case "value":
      return "string | number";
    case "number":
      return "number";
    case "date":
      return "Date | number";
    case "tag":
      return "(chunks: string[]) => string";
    case "select": {
      const options = argument.options
        .filter((option) => option !== "other")
        .map((option) => JSON.stringify(option));
      return [...options, options.length > 0 ? "(string & {})" : "string"].join(
        " | ",
      );
    }
  }
};

/** Text made safe inside a block comment, on one line. */
const prose = (text: string): string => {
  return text.replaceAll("*/", "*\\/").replaceAll(/\s*\n\s*/g, " ");
};

/**
 * One member of the emitted `Arguments` interface: the message key mapped to
 * the values it takes, under a comment carrying the translator note and the
 * source message — what an editor shows on hover.
 */
export const member = (key: string, message: Message): string => {
  const fields = Object.entries(message.arguments).map(
    ([name, argument]) => `${JSON.stringify(name)}: ${type(argument)}`,
  );
  const shape =
    fields.length === 0 ? "Record<never, never>" : `{ ${fields.join("; ")} }`;
  const comment = [
    "  /**",
    ...(message.description === undefined
      ? []
      : [`   * ${prose(message.description)}`, "   *"]),
    `   * \`${prose(message.source)}\``,
    "   */",
  ];
  return [...comment, `  ${JSON.stringify(key)}: ${shape};`].join("\n");
};

/**
 * A module and its declarations, emitted side by side. `.d.mts` is what
 * TypeScript pairs with an `.mjs` under every module resolution, including a
 * relative `import "./fibber/index.mjs"` in an app.
 *
 * @param name - The module's name, without an extension.
 * @param mjs - The module's source lines.
 * @param dts - The declaration's source lines.
 */
export const pair = (
  name: string,
  mjs: string[],
  dts: string[],
): OutputFile[] => {
  return [
    { path: `${name}.mjs`, contents: `${mjs.join("\n")}\n` },
    { path: `${name}.d.mts`, contents: `${dts.join("\n")}\n` },
  ];
};
