import { describe, expect, it } from "vitest";

import { generate } from "../src/generate";
import { CONFIG, FIXTURES } from "./helpers";

/** The contents of one generated file. */
const file = async (path: string): Promise<string> => {
  const output = await generate(CONFIG, { cwd: FIXTURES });
  const found = output.files.find((candidate) => candidate.path === path);
  if (found === undefined) {
    throw new Error(`no ${path} in the output`);
  }
  return found.contents;
};

describe("generate", () => {
  it("emits the contract module and a bundle per locale", async () => {
    const output = await generate(CONFIG, { cwd: FIXTURES });
    expect(output.outDir).toBe("fibber");
    expect(output.files.map((candidate) => candidate.path)).toEqual([
      "index.mjs",
      "index.d.mts",
      "bundles.mjs",
      "bundles.d.mts",
      "locales/en.mjs",
      "locales/fr.mjs",
    ]);
    expect(output.coverage.fr?.missing).toEqual(["invite", "total", "terms"]);
  });

  it("types each message's arguments off its source", async () => {
    expect(await file("index.d.mts")).toMatchInlineSnapshot(`
      "// Generated by @fibber/kit. Do not edit by hand.
      export type Locale =
        | "en"
        | "fr";
      export type Key =
        | "greeting"
        | "title"
        | "inbox"
        | "invite"
        | "total"
        | "terms";
      export type Document = never;
      export interface Arguments {
        /**
         * Greets the signed-in user by name.
         *
         * \`Hello, {name}!\`
         */
        "greeting": { "name": string | number };
        /**
         * \`Welcome\`
         */
        "title": Record<never, never>;
        /**
         * Unread count in the header.
         *
         * \`{count, plural, one {# new message} other {# new messages}}\`
         */
        "inbox": { "count": number };
        /**
         * \`{gender, select, female {She invited you} male {He invited you} other {They invited you}} on {at, date, ::yMMMd}\`
         */
        "invite": { "gender": "female" | "male" | (string & {}); "at": Date | number };
        /**
         * \`{amount, number, price} due {due, date, long}\`
         */
        "total": { "amount": number; "due": Date | number };
        /**
         * \`Read the <link>terms</link>\`
         */
        "terms": { "link": (chunks: string[]) => string };
      }
      export declare const locale: "en";
      export declare const locales: readonly Locale[];
      export declare const messages: readonly Key[];
      export declare const documents: readonly Document[];
      export declare const isLocale: (value: unknown) => value is Locale;
      export declare const isKey: (value: unknown) => value is Key;
      export declare const contract: {
        readonly locale: "en";
        readonly locales: readonly Locale[];
        readonly messages: readonly Key[];
        readonly formats: {
          readonly number: { readonly "price": Intl.NumberFormatOptions };
          readonly date: Record<never, never>;
          readonly time: Record<never, never>;
        };
        /** Never present at runtime; carries each message's values in the types. */
        readonly arguments?: Arguments;
      };
      export type Contract = typeof contract;
      "
    `);
  });

  it("exports the lists and guards, and no message text", async () => {
    const source = await file("index.mjs");
    expect(source).not.toContain("Hello");
    const module = await import(
      `data:text/javascript,${encodeURIComponent(source)}`
    );
    expect(module.locale).toBe("en");
    expect(module.locales).toEqual(["en", "fr"]);
    expect(module.messages).toContain("greeting");
    expect(module.isLocale("fr")).toBe(true);
    expect(module.isLocale("de")).toBe(false);
    expect(module.isKey("greeting")).toBe(true);
    expect(module.isKey(7)).toBe(false);
    expect(module.contract).toEqual({
      locale: "en",
      locales: ["en", "fr"],
      messages: module.messages,
      formats: {
        number: { price: { style: "currency", currency: "EUR" } },
        date: {},
        time: {},
      },
    });
  });

  it("emits a lazy loader per locale", async () => {
    const source = await file("bundles.mjs");
    expect(source).toContain('"fr": () => import("./locales/fr.mjs")');
    expect(await file("bundles.d.mts")).toContain(
      "readonly [L in Locale]: () => Promise<Bundle<Contract>>;",
    );
  });

  it("emits each bundle as a compact module keyed by message", async () => {
    const parse = (source: string) =>
      JSON.parse(source.replace(/^export default /, "").replace(/;\n$/, ""));
    const bundle = await file("locales/fr.mjs");
    expect(bundle).toMatch(/^export default \{.*\};\n$/);
    expect(parse(bundle).title).toEqual([{ type: 0, value: "Bienvenue" }]);
    expect(Object.keys(parse(bundle))).toEqual(
      Object.keys(parse(await file("locales/en.mjs"))),
    );
  });

  it("emits an empty contract for a source with no messages", async () => {
    const output = await generate(
      { source: "empty.json", locale: "en" },
      { cwd: FIXTURES },
    );
    const dts = output.files.find(
      (candidate) => candidate.path === "index.d.mts",
    );
    expect(dts?.contents).toContain("export type Key = never;");
    expect(dts?.contents).toContain("export interface Arguments {}");
  });
});
